insert into userinfo (name, username, email, city) values ('Harwilll', 'hhawksley0', 'hsiemianowicz0@blogspot.com', 'Eskilstuna');
insert into userinfo (name, username, email, city) values ('Ogdan', 'ojarnell1', 'osille1@usa.gov', 'Baitashan');
insert into userinfo (name, username, email, city) values ('Deedee', 'dhackwell2', 'dbillinge2@oracle.com', 'Tikiw');
insert into userinfo (name, username, email, city) values ('Cornelius', 'ckelland3', 'chaxell3@upenn.edu', 'Singajaya');
insert into userinfo (name, username, email, city) values ('Eachelle', 'efontaine4', 'emaseres4@statcounter.com', 'Magugu');
insert into userinfo (name, username, email, city) values ('Ronnie', 'rgant5', 'riannitti5@t-online.de', 'Xinshao');
insert into userinfo (name, username, email, city) values ('Fan', 'fbeckhouse6', 'fdunge6@berkeley.edu', 'Zheleznodorozhnyy');
insert into userinfo (name, username, email, city) values ('Milli', 'mfalconer7', 'mlavrinov7@etsy.com', 'La Plaine-Saint-Denis');
insert into userinfo (name, username, email, city) values ('Pincas', 'pgaiger8', 'plusher8@hugedomains.com', 'Cerro Azul');
insert into userinfo (name, username, email, city) values ('Redford', 'randreassen9', 'rparamor9@vimeo.com', 'Lunel');

insert into trails (name, location, length, elevation_gain, difficulty, avg_rating) values ('Norway Maple', 'California', 5.5, 6057, 'very_difficult', 7.23);
insert into trails (name, location, length, elevation_gain, difficulty, avg_rating) values ('Carioca', 'Connecticut', 7.1, 2680, 'difficult', 7.11);
insert into trails (name, location, length, elevation_gain, difficulty, avg_rating) values ('Stang', 'Texas', 5.5, 1418, 'moderate', 1.18);
insert into trails (name, location, length, elevation_gain, difficulty, avg_rating) values ('Vahlen', 'Virginia', 9.7, 1190, 'moderate', 5.35);
insert into trails (name, location, length, elevation_gain, difficulty, avg_rating) values ('Hovde', 'North Carolina', 7.9, 3365, 'easy', 9.63);
insert into trails (name, location, length, elevation_gain, difficulty, avg_rating) values ('Michigan', 'Illinois', 3.1, 5266, 'very_difficult', 6.71);
insert into trails (name, location, length, elevation_gain, difficulty, avg_rating) values ('Londonderry', 'New York', 4.3, 5029, 'difficult', 2.31);
insert into trails (name, location, length, elevation_gain, difficulty, avg_rating) values ('Bay', 'Mississippi', 3.3, 6214, 'easy', 2.77);
insert into trails (name, location, length, elevation_gain, difficulty, avg_rating) values ('Miller', 'Nevada', 9.3, 3590, 'difficult', 3.26);
insert into trails (name, location, length, elevation_gain, difficulty, avg_rating) values ('Northland', 'Louisiana', 3.6, 6531, 'difficult', 1.38);
insert into trails (name, location, length, elevation_gain, difficulty, avg_rating) values ('Reinke', 'California', 4.6, 2844, 'difficult', 7.68);
insert into trails (name, location, length, elevation_gain, difficulty, avg_rating) values ('Bobwhite', 'Indiana', 7.6, 5592, 'difficult', 3.87);
insert into trails (name, location, length, elevation_gain, difficulty, avg_rating) values ('Sycamore', 'Virginia', 2.4, 1171, 'difficult', 8.05);
insert into trails (name, location, length, elevation_gain, difficulty, avg_rating) values ('Magdeline', 'Georgia', 7.2, 6857, 'difficult', 2.2);
insert into trails (name, location, length, elevation_gain, difficulty, avg_rating) values ('Mcbride', 'Florida', 6.4, 2377, 'very_difficult', 2.33);
insert into trails (name, location, length, elevation_gain, difficulty, avg_rating) values ('Maryland', 'California', 5.7, 5630, 'easy', 2.51);
insert into trails (name, location, length, elevation_gain, difficulty, avg_rating) values ('Golden Leaf', 'Connecticut', 2.2, 1605, 'very_difficult', 5.55);
insert into trails (name, location, length, elevation_gain, difficulty, avg_rating) values ('Ramsey', 'Missouri', 8.7, 1829, 'very_difficult', 8.59);
insert into trails (name, location, length, elevation_gain, difficulty, avg_rating) values ('Waxwing', 'Utah', 8.9, 2809, 'difficult', 1.2);
insert into trails (name, location, length, elevation_gain, difficulty, avg_rating) values ('Roxbury', 'California', 6.6, 2224, 'easy', 8.15);
