insert into reviews (trail_id, user_id, review, rating) values (10, 1, 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 9.71);
insert into reviews (trail_id, user_id, review, rating) values (11, 1, 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 4.17);
insert into reviews (trail_id, user_id, review, rating) values (12, 1, 'Maecenas pulvinar lobortis est. Phasellus sit amet erat.', 8.93);
insert into reviews (trail_id, user_id, review, rating) values (13, 1, 'Suspendisse potenti.', 1.39);
insert into reviews (trail_id, user_id, review, rating) values (14, 1, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 5.36);
insert into reviews (trail_id, user_id, review, rating) values (15, 1, 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 7.15);
insert into reviews (trail_id, user_id, review, rating) values (16, 1, 'Nullam varius.', 8.28);
insert into reviews (trail_id, user_id, review, rating) values (17, 1, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 8.77);
insert into reviews (trail_id, user_id, review, rating) values (18, 1, 'Nulla mollis molestie lorem.', 9.33);
insert into reviews (trail_id, user_id, review, rating) values (19, 1, 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 2.01);
insert into reviews (trail_id, user_id, review, rating) values (1, 1, 'Curabitur convallis.', 2.22);
insert into reviews (trail_id, user_id, review, rating) values (3, 1, 'Duis mattis egestas metus. Aenean fermentum.', 6.49);
insert into reviews (trail_id, user_id, review, rating) values (5, 1, 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', 7.26);
insert into reviews (trail_id, user_id, review, rating) values (7, 1, 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', 4.02);
insert into reviews (trail_id, user_id, review, rating) values (7, 1, 'Vestibulum ac est lacinia nisi venenatis tristique.', 1.87);
insert into reviews (trail_id, user_id, review, rating) values (7, 1, 'Sed ante.', 2.03);
insert into reviews (trail_id, user_id, review, rating) values (9, 1, 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 4.17);
insert into reviews (trail_id, user_id, review, rating) values (9, 1, 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', 3.06);
insert into reviews (trail_id, user_id, review, rating) values (2, 1, 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 7.7);
insert into reviews (trail_id, user_id, review, rating) values (20, 1, 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 4.74);
insert into reviews (trail_id, user_id, review, rating) values (2, 1, 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', 5.1);
insert into reviews (trail_id, user_id, review, rating) values (3, 1, 'Duis mattis egestas metus.', 7.03);
insert into reviews (trail_id, user_id, review, rating) values (4, 1, 'Proin risus. Praesent lectus.', 9.79);
insert into reviews (trail_id, user_id, review, rating) values (5, 1, 'Nulla ut erat id mauris vulputate elementum.', 3.88);
insert into reviews (trail_id, user_id, review, rating) values (6, 1, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', 5.77);
insert into reviews (trail_id, user_id, review, rating) values (7, 1, 'Morbi quis tortor id nulla ultrices aliquet.', 8.25);
insert into reviews (trail_id, user_id, review, rating) values (8, 1, 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 6.71);
insert into reviews (trail_id, user_id, review, rating) values (19, 1, 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 1.91);
insert into reviews (trail_id, user_id, review, rating) values (9, 1, 'Integer tincidunt ante vel ipsum.', 2.05);
insert into reviews (trail_id, user_id, review, rating) values (8, 1, 'Nunc rhoncus dui vel sem.', 8.73);
