name: Run Production BDD Tests Against Deployed Website

on:
  push:
    branches:
      - master
  workflow_dispatch: 
  
jobs:
  run-bdd-post-deploy:
    runs-on: 'ubuntu-latest'

    steps:
        - name: Check out repository
          uses: actions/checkout@v2

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
              node-version: ${{ matrix.node-version }}
              cache: 'npm'
        - run: npm ci
        - run: npm cuke
        - run: echo "All Done!"
