name: Run Production BDD Tests Against Deployed Website

on:
  push:
    branches:
      - master
  workflow_dispatch: 
  
jobs:
  run-bdd-post-deploy:
    runs-on: 'ubuntu-latest'

    steps:
        - name: Check out repository
          uses: actions/checkout@v2

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
              node-version: ${{ matrix.node-version }}
              cache: 'npm'
        - run: npm ci
        - run: npm cuke
        - run: echo "All Done!"
        - name: Test Report
          uses: dorny/test-reporter@v1
          if: success() || failure()    # run this step even if previous step failed
          with:
            name: BDD Tests                # Name of the check run which will be created
            path: cucumber-report.html     # Path to test results
            reporter: cucumber-html        # Format of test results