name: Run Production BDD Tests Against Deployed Website

on:
  push:
    branches:
      - master
  workflow_dispatch: 
  
jobs:
  run-bdd-post-deploy:
    runs-on: 'ubuntu-latest'

    steps:
        - name: Check out repository
          uses: actions/checkout@v2

        - name: Use Node.js 20.x
          uses: actions/setup-node@v3
          with:
              node-version: '20.x'
              cache: 'npm'
        - run: npm ci
        - run: npm run cuke
        - run: echo "All Done!"
        - name: Publish Test Report to GitHub Pages
          uses: PavanMudigonda/html-reporter-github-pages/composite@v1.1
          with:
            test_results: test-reports
            gh_pages: gh_pages
            results_history: results-history
            keep_reports: 10
        - name: Publish Github Pages
          if: ${{ always() }}
          uses: peaceiris/actions-gh-pages@v3.8.0
          with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_branch: gh-Pages
              publish_dir: test-reports
              keep_files: true   
        # - name: Post the link to the report
        #   if: always()
        #   uses: Sibz/github-status-action@v1
        #   with: 
        #       authToken: ${{secrets.GITHUB_TOKEN}}
        #       context: 'Test report'
        #       state: 'success'
        #       sha: ${{ github.event.pull_request.head.sha }}
        #       target_url: billwright.github.io/html-reporter-github-pages/${{ github.run_number }}